type PictureProps = {
  src: string;
  alt: string;
  className?: string;
  width?: number;
  height?: number;
  loading?: "eager" | "lazy";
  fetchPriority?: "high" | "low" | "auto";
};

// Renders AVIF/WebP sources alongside the JPEG fallback. Only use this for
// images that actually have .webp/.avif siblings on disk (generated by
// scripts/optimize-images.js) — picking a <source> the browser then fails
// to fetch does not fall back to the next one.
export default function Picture({
  src,
  alt,
  className,
  width,
  height,
  loading = "lazy",
  fetchPriority,
}: PictureProps) {
  const avif = src.replace(/\.jpe?g$/i, ".avif");
  const webp = src.replace(/\.jpe?g$/i, ".webp");

  return (
    <picture>
      <source srcSet={avif} type="image/avif" />
      <source srcSet={webp} type="image/webp" />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={src}
        alt={alt}
        className={className}
        width={width}
        height={height}
        loading={loading}
        fetchPriority={fetchPriority}
      />
    </picture>
  );
}
