// AUTO-GENERATED by build-galleries.js — do not edit by hand.
export type Photo = { thumb: string; full: string; w: number; h: number };
export type Project = {
  slug: string;
  name: string;
  category: string;
  location: string;
  featured: boolean;
  cover: string;
  coverWidth: number;
  coverHeight: number;
  count: number;
  photos: Photo[];
};

export const projects: Project[] = [
  {
    "slug": "amit-anuj",
    "name": "Amit & Anuj",
    "category": "Mehendi & Haldi",
    "location": "Himachal Pradesh",
    "featured": true,
    "cover": "/projects/amit-anuj/cover.jpg",
    "count": 31,
    "photos": [
      {
        "thumb": "/projects/amit-anuj/t/001.jpg",
        "full": "/projects/amit-anuj/f/001.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/002.jpg",
        "full": "/projects/amit-anuj/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/003.jpg",
        "full": "/projects/amit-anuj/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/004.jpg",
        "full": "/projects/amit-anuj/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/005.jpg",
        "full": "/projects/amit-anuj/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/006.jpg",
        "full": "/projects/amit-anuj/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/007.jpg",
        "full": "/projects/amit-anuj/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/008.jpg",
        "full": "/projects/amit-anuj/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/009.jpg",
        "full": "/projects/amit-anuj/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/010.jpg",
        "full": "/projects/amit-anuj/f/010.jpg",
        "w": 1600,
        "h": 2071
      },
      {
        "thumb": "/projects/amit-anuj/t/011.jpg",
        "full": "/projects/amit-anuj/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/012.jpg",
        "full": "/projects/amit-anuj/f/012.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/013.jpg",
        "full": "/projects/amit-anuj/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/014.jpg",
        "full": "/projects/amit-anuj/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/015.jpg",
        "full": "/projects/amit-anuj/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/016.jpg",
        "full": "/projects/amit-anuj/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/017.jpg",
        "full": "/projects/amit-anuj/f/017.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/amit-anuj/t/018.jpg",
        "full": "/projects/amit-anuj/f/018.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/019.jpg",
        "full": "/projects/amit-anuj/f/019.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/020.jpg",
        "full": "/projects/amit-anuj/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/021.jpg",
        "full": "/projects/amit-anuj/f/021.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/022.jpg",
        "full": "/projects/amit-anuj/f/022.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/023.jpg",
        "full": "/projects/amit-anuj/f/023.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/024.jpg",
        "full": "/projects/amit-anuj/f/024.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/025.jpg",
        "full": "/projects/amit-anuj/f/025.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/026.jpg",
        "full": "/projects/amit-anuj/f/026.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/027.jpg",
        "full": "/projects/amit-anuj/f/027.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/amit-anuj/t/028.jpg",
        "full": "/projects/amit-anuj/f/028.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/029.jpg",
        "full": "/projects/amit-anuj/f/029.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/030.jpg",
        "full": "/projects/amit-anuj/f/030.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/amit-anuj/t/031.jpg",
        "full": "/projects/amit-anuj/f/031.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 800
  },
  {
    "slug": "tenzin-dev",
    "name": "Tenzin & Dev",
    "category": "Mehendi & Haldi",
    "location": "Manali, Himachal Pradesh",
    "featured": true,
    "cover": "/projects/tenzin-dev/cover.jpg",
    "count": 50,
    "photos": [
      {
        "thumb": "/projects/tenzin-dev/t/001.jpg",
        "full": "/projects/tenzin-dev/f/001.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/002.jpg",
        "full": "/projects/tenzin-dev/f/002.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/003.jpg",
        "full": "/projects/tenzin-dev/f/003.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/004.jpg",
        "full": "/projects/tenzin-dev/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/005.jpg",
        "full": "/projects/tenzin-dev/f/005.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/006.jpg",
        "full": "/projects/tenzin-dev/f/006.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/007.jpg",
        "full": "/projects/tenzin-dev/f/007.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/008.jpg",
        "full": "/projects/tenzin-dev/f/008.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/009.jpg",
        "full": "/projects/tenzin-dev/f/009.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/010.jpg",
        "full": "/projects/tenzin-dev/f/010.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/011.jpg",
        "full": "/projects/tenzin-dev/f/011.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/012.jpg",
        "full": "/projects/tenzin-dev/f/012.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/013.jpg",
        "full": "/projects/tenzin-dev/f/013.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/014.jpg",
        "full": "/projects/tenzin-dev/f/014.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/015.jpg",
        "full": "/projects/tenzin-dev/f/015.jpg",
        "w": 1600,
        "h": 2401
      },
      {
        "thumb": "/projects/tenzin-dev/t/016.jpg",
        "full": "/projects/tenzin-dev/f/016.jpg",
        "w": 1600,
        "h": 2399
      },
      {
        "thumb": "/projects/tenzin-dev/t/017.jpg",
        "full": "/projects/tenzin-dev/f/017.jpg",
        "w": 1600,
        "h": 2399
      },
      {
        "thumb": "/projects/tenzin-dev/t/018.jpg",
        "full": "/projects/tenzin-dev/f/018.jpg",
        "w": 1600,
        "h": 2399
      },
      {
        "thumb": "/projects/tenzin-dev/t/019.jpg",
        "full": "/projects/tenzin-dev/f/019.jpg",
        "w": 1600,
        "h": 2399
      },
      {
        "thumb": "/projects/tenzin-dev/t/020.jpg",
        "full": "/projects/tenzin-dev/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/021.jpg",
        "full": "/projects/tenzin-dev/f/021.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/022.jpg",
        "full": "/projects/tenzin-dev/f/022.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/023.jpg",
        "full": "/projects/tenzin-dev/f/023.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/024.jpg",
        "full": "/projects/tenzin-dev/f/024.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/025.jpg",
        "full": "/projects/tenzin-dev/f/025.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/026.jpg",
        "full": "/projects/tenzin-dev/f/026.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/027.jpg",
        "full": "/projects/tenzin-dev/f/027.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/028.jpg",
        "full": "/projects/tenzin-dev/f/028.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/029.jpg",
        "full": "/projects/tenzin-dev/f/029.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/030.jpg",
        "full": "/projects/tenzin-dev/f/030.jpg",
        "w": 1600,
        "h": 2399
      },
      {
        "thumb": "/projects/tenzin-dev/t/031.jpg",
        "full": "/projects/tenzin-dev/f/031.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/032.jpg",
        "full": "/projects/tenzin-dev/f/032.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/033.jpg",
        "full": "/projects/tenzin-dev/f/033.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/034.jpg",
        "full": "/projects/tenzin-dev/f/034.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/035.jpg",
        "full": "/projects/tenzin-dev/f/035.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/036.jpg",
        "full": "/projects/tenzin-dev/f/036.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/037.jpg",
        "full": "/projects/tenzin-dev/f/037.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/038.jpg",
        "full": "/projects/tenzin-dev/f/038.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/039.jpg",
        "full": "/projects/tenzin-dev/f/039.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/040.jpg",
        "full": "/projects/tenzin-dev/f/040.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/041.jpg",
        "full": "/projects/tenzin-dev/f/041.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/042.jpg",
        "full": "/projects/tenzin-dev/f/042.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/043.jpg",
        "full": "/projects/tenzin-dev/f/043.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/044.jpg",
        "full": "/projects/tenzin-dev/f/044.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/045.jpg",
        "full": "/projects/tenzin-dev/f/045.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/046.jpg",
        "full": "/projects/tenzin-dev/f/046.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/047.jpg",
        "full": "/projects/tenzin-dev/f/047.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/tenzin-dev/t/048.jpg",
        "full": "/projects/tenzin-dev/f/048.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/tenzin-dev/t/049.jpg",
        "full": "/projects/tenzin-dev/f/049.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/tenzin-dev/t/050.jpg",
        "full": "/projects/tenzin-dev/f/050.jpg",
        "w": 1600,
        "h": 1067
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 800
  },
  {
    "slug": "sofia-sameer",
    "name": "Sofia & Sameer",
    "category": "Wedding",
    "location": "Manali, Himachal Pradesh",
    "featured": true,
    "cover": "/projects/sofia-sameer/cover.jpg",
    "count": 42,
    "photos": [
      {
        "thumb": "/projects/sofia-sameer/t/001.jpg",
        "full": "/projects/sofia-sameer/f/001.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/002.jpg",
        "full": "/projects/sofia-sameer/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/003.jpg",
        "full": "/projects/sofia-sameer/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/004.jpg",
        "full": "/projects/sofia-sameer/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/005.jpg",
        "full": "/projects/sofia-sameer/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/006.jpg",
        "full": "/projects/sofia-sameer/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/007.jpg",
        "full": "/projects/sofia-sameer/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/008.jpg",
        "full": "/projects/sofia-sameer/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/009.jpg",
        "full": "/projects/sofia-sameer/f/009.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/010.jpg",
        "full": "/projects/sofia-sameer/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/011.jpg",
        "full": "/projects/sofia-sameer/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/012.jpg",
        "full": "/projects/sofia-sameer/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/013.jpg",
        "full": "/projects/sofia-sameer/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/014.jpg",
        "full": "/projects/sofia-sameer/f/014.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/015.jpg",
        "full": "/projects/sofia-sameer/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/016.jpg",
        "full": "/projects/sofia-sameer/f/016.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/017.jpg",
        "full": "/projects/sofia-sameer/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/018.jpg",
        "full": "/projects/sofia-sameer/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/019.jpg",
        "full": "/projects/sofia-sameer/f/019.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/020.jpg",
        "full": "/projects/sofia-sameer/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/021.jpg",
        "full": "/projects/sofia-sameer/f/021.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/022.jpg",
        "full": "/projects/sofia-sameer/f/022.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/023.jpg",
        "full": "/projects/sofia-sameer/f/023.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/024.jpg",
        "full": "/projects/sofia-sameer/f/024.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/025.jpg",
        "full": "/projects/sofia-sameer/f/025.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/026.jpg",
        "full": "/projects/sofia-sameer/f/026.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/027.jpg",
        "full": "/projects/sofia-sameer/f/027.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/028.jpg",
        "full": "/projects/sofia-sameer/f/028.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/029.jpg",
        "full": "/projects/sofia-sameer/f/029.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/sofia-sameer/t/030.jpg",
        "full": "/projects/sofia-sameer/f/030.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/sofia-sameer/t/031.jpg",
        "full": "/projects/sofia-sameer/f/031.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/032.jpg",
        "full": "/projects/sofia-sameer/f/032.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/033.jpg",
        "full": "/projects/sofia-sameer/f/033.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/034.jpg",
        "full": "/projects/sofia-sameer/f/034.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/035.jpg",
        "full": "/projects/sofia-sameer/f/035.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/036.jpg",
        "full": "/projects/sofia-sameer/f/036.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/037.jpg",
        "full": "/projects/sofia-sameer/f/037.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/038.jpg",
        "full": "/projects/sofia-sameer/f/038.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/039.jpg",
        "full": "/projects/sofia-sameer/f/039.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/040.jpg",
        "full": "/projects/sofia-sameer/f/040.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/sofia-sameer/t/041.jpg",
        "full": "/projects/sofia-sameer/f/041.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/sofia-sameer/t/042.jpg",
        "full": "/projects/sofia-sameer/f/042.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 800
  },
  {
    "slug": "pratiksha-sayam",
    "name": "Pratiksha & Sayam",
    "category": "Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/pratiksha-sayam/cover.jpg",
    "count": 65,
    "photos": [
      {
        "thumb": "/projects/pratiksha-sayam/t/001.jpg",
        "full": "/projects/pratiksha-sayam/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/002.jpg",
        "full": "/projects/pratiksha-sayam/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/003.jpg",
        "full": "/projects/pratiksha-sayam/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/004.jpg",
        "full": "/projects/pratiksha-sayam/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/005.jpg",
        "full": "/projects/pratiksha-sayam/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/006.jpg",
        "full": "/projects/pratiksha-sayam/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/007.jpg",
        "full": "/projects/pratiksha-sayam/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/008.jpg",
        "full": "/projects/pratiksha-sayam/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/009.jpg",
        "full": "/projects/pratiksha-sayam/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/010.jpg",
        "full": "/projects/pratiksha-sayam/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/011.jpg",
        "full": "/projects/pratiksha-sayam/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/012.jpg",
        "full": "/projects/pratiksha-sayam/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/013.jpg",
        "full": "/projects/pratiksha-sayam/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/014.jpg",
        "full": "/projects/pratiksha-sayam/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/015.jpg",
        "full": "/projects/pratiksha-sayam/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/016.jpg",
        "full": "/projects/pratiksha-sayam/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/017.jpg",
        "full": "/projects/pratiksha-sayam/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/018.jpg",
        "full": "/projects/pratiksha-sayam/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/019.jpg",
        "full": "/projects/pratiksha-sayam/f/019.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/020.jpg",
        "full": "/projects/pratiksha-sayam/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/021.jpg",
        "full": "/projects/pratiksha-sayam/f/021.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/022.jpg",
        "full": "/projects/pratiksha-sayam/f/022.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/023.jpg",
        "full": "/projects/pratiksha-sayam/f/023.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/024.jpg",
        "full": "/projects/pratiksha-sayam/f/024.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/025.jpg",
        "full": "/projects/pratiksha-sayam/f/025.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/026.jpg",
        "full": "/projects/pratiksha-sayam/f/026.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/027.jpg",
        "full": "/projects/pratiksha-sayam/f/027.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/028.jpg",
        "full": "/projects/pratiksha-sayam/f/028.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/029.jpg",
        "full": "/projects/pratiksha-sayam/f/029.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/030.jpg",
        "full": "/projects/pratiksha-sayam/f/030.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/031.jpg",
        "full": "/projects/pratiksha-sayam/f/031.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/032.jpg",
        "full": "/projects/pratiksha-sayam/f/032.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/033.jpg",
        "full": "/projects/pratiksha-sayam/f/033.jpg",
        "w": 1600,
        "h": 2071
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/034.jpg",
        "full": "/projects/pratiksha-sayam/f/034.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/035.jpg",
        "full": "/projects/pratiksha-sayam/f/035.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/036.jpg",
        "full": "/projects/pratiksha-sayam/f/036.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/037.jpg",
        "full": "/projects/pratiksha-sayam/f/037.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/038.jpg",
        "full": "/projects/pratiksha-sayam/f/038.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/039.jpg",
        "full": "/projects/pratiksha-sayam/f/039.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/040.jpg",
        "full": "/projects/pratiksha-sayam/f/040.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/041.jpg",
        "full": "/projects/pratiksha-sayam/f/041.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/042.jpg",
        "full": "/projects/pratiksha-sayam/f/042.jpg",
        "w": 1600,
        "h": 2070
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/043.jpg",
        "full": "/projects/pratiksha-sayam/f/043.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/044.jpg",
        "full": "/projects/pratiksha-sayam/f/044.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/045.jpg",
        "full": "/projects/pratiksha-sayam/f/045.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/046.jpg",
        "full": "/projects/pratiksha-sayam/f/046.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/047.jpg",
        "full": "/projects/pratiksha-sayam/f/047.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/048.jpg",
        "full": "/projects/pratiksha-sayam/f/048.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/049.jpg",
        "full": "/projects/pratiksha-sayam/f/049.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/050.jpg",
        "full": "/projects/pratiksha-sayam/f/050.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/051.jpg",
        "full": "/projects/pratiksha-sayam/f/051.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/052.jpg",
        "full": "/projects/pratiksha-sayam/f/052.jpg",
        "w": 1600,
        "h": 1143
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/053.jpg",
        "full": "/projects/pratiksha-sayam/f/053.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/054.jpg",
        "full": "/projects/pratiksha-sayam/f/054.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/055.jpg",
        "full": "/projects/pratiksha-sayam/f/055.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/056.jpg",
        "full": "/projects/pratiksha-sayam/f/056.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/057.jpg",
        "full": "/projects/pratiksha-sayam/f/057.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/058.jpg",
        "full": "/projects/pratiksha-sayam/f/058.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/059.jpg",
        "full": "/projects/pratiksha-sayam/f/059.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/060.jpg",
        "full": "/projects/pratiksha-sayam/f/060.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/061.jpg",
        "full": "/projects/pratiksha-sayam/f/061.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/062.jpg",
        "full": "/projects/pratiksha-sayam/f/062.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/063.jpg",
        "full": "/projects/pratiksha-sayam/f/063.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/064.jpg",
        "full": "/projects/pratiksha-sayam/f/064.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/pratiksha-sayam/t/065.jpg",
        "full": "/projects/pratiksha-sayam/f/065.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1800
  },
  {
    "slug": "yogesh-shivani",
    "name": "Yogesh & Shivani",
    "category": "Pre-Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/yogesh-shivani/cover.jpg",
    "count": 35,
    "photos": [
      {
        "thumb": "/projects/yogesh-shivani/t/001.jpg",
        "full": "/projects/yogesh-shivani/f/001.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/yogesh-shivani/t/002.jpg",
        "full": "/projects/yogesh-shivani/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/003.jpg",
        "full": "/projects/yogesh-shivani/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/004.jpg",
        "full": "/projects/yogesh-shivani/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/005.jpg",
        "full": "/projects/yogesh-shivani/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/006.jpg",
        "full": "/projects/yogesh-shivani/f/006.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/yogesh-shivani/t/007.jpg",
        "full": "/projects/yogesh-shivani/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/008.jpg",
        "full": "/projects/yogesh-shivani/f/008.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/yogesh-shivani/t/009.jpg",
        "full": "/projects/yogesh-shivani/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/010.jpg",
        "full": "/projects/yogesh-shivani/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/011.jpg",
        "full": "/projects/yogesh-shivani/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/012.jpg",
        "full": "/projects/yogesh-shivani/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/013.jpg",
        "full": "/projects/yogesh-shivani/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/014.jpg",
        "full": "/projects/yogesh-shivani/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/015.jpg",
        "full": "/projects/yogesh-shivani/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/016.jpg",
        "full": "/projects/yogesh-shivani/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/017.jpg",
        "full": "/projects/yogesh-shivani/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/018.jpg",
        "full": "/projects/yogesh-shivani/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/019.jpg",
        "full": "/projects/yogesh-shivani/f/019.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/020.jpg",
        "full": "/projects/yogesh-shivani/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/021.jpg",
        "full": "/projects/yogesh-shivani/f/021.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/022.jpg",
        "full": "/projects/yogesh-shivani/f/022.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/023.jpg",
        "full": "/projects/yogesh-shivani/f/023.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/024.jpg",
        "full": "/projects/yogesh-shivani/f/024.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/025.jpg",
        "full": "/projects/yogesh-shivani/f/025.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/026.jpg",
        "full": "/projects/yogesh-shivani/f/026.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/027.jpg",
        "full": "/projects/yogesh-shivani/f/027.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/028.jpg",
        "full": "/projects/yogesh-shivani/f/028.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/yogesh-shivani/t/029.jpg",
        "full": "/projects/yogesh-shivani/f/029.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/030.jpg",
        "full": "/projects/yogesh-shivani/f/030.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/031.jpg",
        "full": "/projects/yogesh-shivani/f/031.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/032.jpg",
        "full": "/projects/yogesh-shivani/f/032.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/033.jpg",
        "full": "/projects/yogesh-shivani/f/033.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/034.jpg",
        "full": "/projects/yogesh-shivani/f/034.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/yogesh-shivani/t/035.jpg",
        "full": "/projects/yogesh-shivani/f/035.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 800
  },
  {
    "slug": "aashima-chandel",
    "name": "Aashima Chandel",
    "category": "Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/aashima-chandel/cover.jpg",
    "count": 21,
    "photos": [
      {
        "thumb": "/projects/aashima-chandel/t/001.jpg",
        "full": "/projects/aashima-chandel/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/002.jpg",
        "full": "/projects/aashima-chandel/f/002.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/aashima-chandel/t/003.jpg",
        "full": "/projects/aashima-chandel/f/003.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/aashima-chandel/t/004.jpg",
        "full": "/projects/aashima-chandel/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/005.jpg",
        "full": "/projects/aashima-chandel/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/006.jpg",
        "full": "/projects/aashima-chandel/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/007.jpg",
        "full": "/projects/aashima-chandel/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/008.jpg",
        "full": "/projects/aashima-chandel/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/009.jpg",
        "full": "/projects/aashima-chandel/f/009.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/aashima-chandel/t/010.jpg",
        "full": "/projects/aashima-chandel/f/010.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/aashima-chandel/t/011.jpg",
        "full": "/projects/aashima-chandel/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/012.jpg",
        "full": "/projects/aashima-chandel/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/013.jpg",
        "full": "/projects/aashima-chandel/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/014.jpg",
        "full": "/projects/aashima-chandel/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/015.jpg",
        "full": "/projects/aashima-chandel/f/015.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/aashima-chandel/t/016.jpg",
        "full": "/projects/aashima-chandel/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/017.jpg",
        "full": "/projects/aashima-chandel/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/018.jpg",
        "full": "/projects/aashima-chandel/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/019.jpg",
        "full": "/projects/aashima-chandel/f/019.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/020.jpg",
        "full": "/projects/aashima-chandel/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/aashima-chandel/t/021.jpg",
        "full": "/projects/aashima-chandel/f/021.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1801
  },
  {
    "slug": "neeraj-shagun",
    "name": "Neeraj & Shagun",
    "category": "Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/neeraj-shagun/cover.jpg",
    "count": 21,
    "photos": [
      {
        "thumb": "/projects/neeraj-shagun/t/001.jpg",
        "full": "/projects/neeraj-shagun/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/002.jpg",
        "full": "/projects/neeraj-shagun/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/003.jpg",
        "full": "/projects/neeraj-shagun/f/003.jpg",
        "w": 1600,
        "h": 1066
      },
      {
        "thumb": "/projects/neeraj-shagun/t/004.jpg",
        "full": "/projects/neeraj-shagun/f/004.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/neeraj-shagun/t/005.jpg",
        "full": "/projects/neeraj-shagun/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/006.jpg",
        "full": "/projects/neeraj-shagun/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/007.jpg",
        "full": "/projects/neeraj-shagun/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/008.jpg",
        "full": "/projects/neeraj-shagun/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/009.jpg",
        "full": "/projects/neeraj-shagun/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/010.jpg",
        "full": "/projects/neeraj-shagun/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/011.jpg",
        "full": "/projects/neeraj-shagun/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/012.jpg",
        "full": "/projects/neeraj-shagun/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/013.jpg",
        "full": "/projects/neeraj-shagun/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/014.jpg",
        "full": "/projects/neeraj-shagun/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/015.jpg",
        "full": "/projects/neeraj-shagun/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/016.jpg",
        "full": "/projects/neeraj-shagun/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/017.jpg",
        "full": "/projects/neeraj-shagun/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/018.jpg",
        "full": "/projects/neeraj-shagun/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/019.jpg",
        "full": "/projects/neeraj-shagun/f/019.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/020.jpg",
        "full": "/projects/neeraj-shagun/f/020.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neeraj-shagun/t/021.jpg",
        "full": "/projects/neeraj-shagun/f/021.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1800
  },
  {
    "slug": "neha-maternity",
    "name": "Neha — Maternity",
    "category": "Maternity",
    "location": "Studio Session",
    "featured": false,
    "cover": "/projects/neha-maternity/cover.jpg",
    "count": 23,
    "photos": [
      {
        "thumb": "/projects/neha-maternity/t/001.jpg",
        "full": "/projects/neha-maternity/f/001.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/neha-maternity/t/002.jpg",
        "full": "/projects/neha-maternity/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/003.jpg",
        "full": "/projects/neha-maternity/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/004.jpg",
        "full": "/projects/neha-maternity/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/005.jpg",
        "full": "/projects/neha-maternity/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/006.jpg",
        "full": "/projects/neha-maternity/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/007.jpg",
        "full": "/projects/neha-maternity/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/008.jpg",
        "full": "/projects/neha-maternity/f/008.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/neha-maternity/t/009.jpg",
        "full": "/projects/neha-maternity/f/009.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/neha-maternity/t/010.jpg",
        "full": "/projects/neha-maternity/f/010.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/neha-maternity/t/011.jpg",
        "full": "/projects/neha-maternity/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/012.jpg",
        "full": "/projects/neha-maternity/f/012.jpg",
        "w": 1600,
        "h": 1236
      },
      {
        "thumb": "/projects/neha-maternity/t/013.jpg",
        "full": "/projects/neha-maternity/f/013.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/014.jpg",
        "full": "/projects/neha-maternity/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/015.jpg",
        "full": "/projects/neha-maternity/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/016.jpg",
        "full": "/projects/neha-maternity/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/017.jpg",
        "full": "/projects/neha-maternity/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/018.jpg",
        "full": "/projects/neha-maternity/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/019.jpg",
        "full": "/projects/neha-maternity/f/019.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/neha-maternity/t/020.jpg",
        "full": "/projects/neha-maternity/f/020.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/neha-maternity/t/021.jpg",
        "full": "/projects/neha-maternity/f/021.jpg",
        "w": 1600,
        "h": 2240
      },
      {
        "thumb": "/projects/neha-maternity/t/022.jpg",
        "full": "/projects/neha-maternity/f/022.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/neha-maternity/t/023.jpg",
        "full": "/projects/neha-maternity/f/023.jpg",
        "w": 1600,
        "h": 1067
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 800
  },
  {
    "slug": "vipasha-nikhil",
    "name": "Vipasha & Nikhil",
    "category": "Pre-Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/vipasha-nikhil/cover.jpg",
    "count": 19,
    "photos": [
      {
        "thumb": "/projects/vipasha-nikhil/t/001.jpg",
        "full": "/projects/vipasha-nikhil/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/002.jpg",
        "full": "/projects/vipasha-nikhil/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/003.jpg",
        "full": "/projects/vipasha-nikhil/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/004.jpg",
        "full": "/projects/vipasha-nikhil/f/004.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/005.jpg",
        "full": "/projects/vipasha-nikhil/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/006.jpg",
        "full": "/projects/vipasha-nikhil/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/007.jpg",
        "full": "/projects/vipasha-nikhil/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/008.jpg",
        "full": "/projects/vipasha-nikhil/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/009.jpg",
        "full": "/projects/vipasha-nikhil/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/010.jpg",
        "full": "/projects/vipasha-nikhil/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/011.jpg",
        "full": "/projects/vipasha-nikhil/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/012.jpg",
        "full": "/projects/vipasha-nikhil/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/013.jpg",
        "full": "/projects/vipasha-nikhil/f/013.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/014.jpg",
        "full": "/projects/vipasha-nikhil/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/015.jpg",
        "full": "/projects/vipasha-nikhil/f/015.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/016.jpg",
        "full": "/projects/vipasha-nikhil/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/017.jpg",
        "full": "/projects/vipasha-nikhil/f/017.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/018.jpg",
        "full": "/projects/vipasha-nikhil/f/018.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/vipasha-nikhil/t/019.jpg",
        "full": "/projects/vipasha-nikhil/f/019.jpg",
        "w": 1600,
        "h": 1067
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1800
  },
  {
    "slug": "hitakshi",
    "name": "Hitakshi",
    "category": "Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/hitakshi/cover.jpg",
    "count": 17,
    "photos": [
      {
        "thumb": "/projects/hitakshi/t/001.jpg",
        "full": "/projects/hitakshi/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/002.jpg",
        "full": "/projects/hitakshi/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/003.jpg",
        "full": "/projects/hitakshi/f/003.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/004.jpg",
        "full": "/projects/hitakshi/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/005.jpg",
        "full": "/projects/hitakshi/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/006.jpg",
        "full": "/projects/hitakshi/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/007.jpg",
        "full": "/projects/hitakshi/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/008.jpg",
        "full": "/projects/hitakshi/f/008.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/009.jpg",
        "full": "/projects/hitakshi/f/009.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/010.jpg",
        "full": "/projects/hitakshi/f/010.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/011.jpg",
        "full": "/projects/hitakshi/f/011.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/012.jpg",
        "full": "/projects/hitakshi/f/012.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/013.jpg",
        "full": "/projects/hitakshi/f/013.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/hitakshi/t/014.jpg",
        "full": "/projects/hitakshi/f/014.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/015.jpg",
        "full": "/projects/hitakshi/f/015.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/hitakshi/t/016.jpg",
        "full": "/projects/hitakshi/f/016.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/hitakshi/t/017.jpg",
        "full": "/projects/hitakshi/f/017.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1800
  },
  {
    "slug": "nishant-rashmi",
    "name": "Nishant & Rashmi",
    "category": "Wedding",
    "location": "Himachal Pradesh",
    "featured": false,
    "cover": "/projects/nishant-rashmi/cover.jpg",
    "count": 8,
    "photos": [
      {
        "thumb": "/projects/nishant-rashmi/t/001.jpg",
        "full": "/projects/nishant-rashmi/f/001.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/002.jpg",
        "full": "/projects/nishant-rashmi/f/002.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/003.jpg",
        "full": "/projects/nishant-rashmi/f/003.jpg",
        "w": 1600,
        "h": 1067
      },
      {
        "thumb": "/projects/nishant-rashmi/t/004.jpg",
        "full": "/projects/nishant-rashmi/f/004.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/005.jpg",
        "full": "/projects/nishant-rashmi/f/005.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/006.jpg",
        "full": "/projects/nishant-rashmi/f/006.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/007.jpg",
        "full": "/projects/nishant-rashmi/f/007.jpg",
        "w": 1600,
        "h": 2400
      },
      {
        "thumb": "/projects/nishant-rashmi/t/008.jpg",
        "full": "/projects/nishant-rashmi/f/008.jpg",
        "w": 1600,
        "h": 2400
      }
    ],
    "coverWidth": 1200,
    "coverHeight": 1800
  }
];

export const categories = ["All", ...Array.from(new Set(projects.map((p) => p.category)))];
